{
 "title": "Workshop Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active User Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(app_active_sessions_avg5m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle CPU Usage by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory Available in GB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1073741824",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((1 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}